name: Generate CDN Links

on:
  workflow_dispatch:
  push:
    paths:
      - '**.user.js'
    branches:
      - master

jobs:
  generate-cdn:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate CDN links
        run: |
          # Ensure dist directory exists
          mkdir -p dist
          
          # Find all user.js files and process them
          find . -name "*.user.js" -type f | while read -r file; do
            # Get the filename without path
            filename=$(basename "$file")
            cdn_file="dist/$filename"
            
            # Generate CDN URLs using jsDelivr
            cdn_url="https://cdn.jsdelivr.net/gh/${{ github.repository }}@master/${cdn_file}"
            update_url="https://cdn.jsdelivr.net/gh/${{ github.repository }}@master/${cdn_file}"
            
            # Process file content and update metadata
            awk -v cdn_url="$cdn_url" -v update_url="$update_url" '
            BEGIN { in_metadata = 0; printed_urls = 0 }
            {
              if ($0 ~ /^\/\/ ==UserScript==/) {
                in_metadata = 1
                print $0
                print "// @downloadURL    " cdn_url
                print "// @updateURL      " update_url
                printed_urls = 1
                next
              }
              if (in_metadata && $0 ~ /^\/\/ =+=UserScript=+=/) {
                in_metadata = 0
              }
              if (in_metadata && !printed_urls && ($0 ~ /^\/\/ @downloadURL/ || $0 ~ /^\/\/ @updateURL/)) {
                next  # Skip existing downloadURL and updateURL
              }
              print $0
            }' "$file" > "$cdn_file"
            
            # Stage the new file
            git add "$cdn_file"
          done
          
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Commit and push if there are changes
          if git status --porcelain | grep .; then
            git commit -m "Update CDN links"
            git push
          fi
